version: 1.2
workflows:
  - name: ONT_CleanReads
    subclass: wdl
    primaryDescriptorPath: /wdls/workflows/ONT_CleanReads.wdl
    latestTagAsDefault: 'true'
    authors:
      - orcid: "0000-0002-6006-0641"
  - name: ONT_FixBamHeader
    subclass: wdl
    primaryDescriptorPath: /wdls/workflows/ONT_FixBamHeader.wdl
    latestTagAsDefault: 'true'
    authors:
      - orcid: "0000-0002-6006-0641"
